export const USER_LOGIN = "http://localhost:3001/post/user"
export const USER_REGISTER = "http://localhost:3001/post/userRegister"
export const USER_BY_ID = "http://localhost:3001/get/user?id="
export const ALL_USERS = "http://localhost:3001/get/users"
export const VERIFY_TOKEN = "http://localhost:3001/post/verifyToken"
export const MACHINES = "http://localhost:3001/get/machines?machineGroup="
export const CUTTING_DATA = "http://localhost:3001/get/cuttingData?machine="
export const SAVE_CUTTING_DATA = "http://localhost:3001/post/cuttingData"